-- Adds a distilled single-line "essence" to each diary entry (user role rows),
-- generated by a Haiku call in magnetism-chat at save time. The essence becomes
-- the title of that entry in the left spine of the diary, so the archive itself
-- reads as a column of the person's own life, not chat-log first-N-chars.

alter table public.conversations
  add column if not exists essence text;
